### ISSUE TITLE
Gauge doesn't show up on dashboard

### ISSUE THREAD

**Issue by QBANIN** [colinl/node-red-dashboard-2-ui-gauge-classic#4] opened 2024-06-20 10:27 UTC
NR 3.1.10 + dashboard 2.0 1.11.1 

Gauge doesn't show up on dashboard, there's just empty space.

**Comment by colinl** [comment] 2024-06-20 11:03
Did you restart node red and refresh the browser? 

If you did then open the developer tools console in the browser and see if there's are any errors.

**Comment by QBANIN** [comment] 2024-06-20 11:18
> Did you restart node red and refresh the browser?

Yes, I did.

> 
> If you did then open the developer tools console in the browser and see if there's are any errors.

`/resources/@colinl/node-red-dashboard-2-ui-gauge-classic/ui-gauge-classic.umd.js” zostało zablokowane z powodu niedozwolonego typu MIME („text/html”).
`

"blocked due to forbidden MIME („text/html”)."

**Comment by colinl** [comment] 2024-06-20 11:22
Can you try a different browser?

**Comment by QBANIN** [comment] 2024-06-20 11:28
> Can you try a different browser?

This issue occurs on both Firefox and Brave Browser.

**Comment by colinl** [comment] 2024-06-20 16:47
Are you able to run any third party nodes? The dashboard 2 ui-led for example?

**Comment by QBANIN** [comment] 2024-06-23 20:45
> Are you able to run any third party nodes? The dashboard 2 ui-led for example?

no, it doesn't work either

**Comment by colinl** [comment] 2024-06-24 19:28
Sorry for the delay I have been on the road.
Since the issue is not specific to this node, I have opened a [question on the node red forum](https://discourse.nodered.org/t/d2-third-party-nodes-do-not-appear-blocked-due-to-forbidden-mime-text-html/88916) where hopefully someone will be able to suggest what the problem may be.  Please go over to to the forum to continue the discussion.

**Comment by colinl** [comment] 2024-06-25 07:41
Please post in the forum details about your system, how you installed node red, and the node-red startup log.

**Comment by QBANIN** [comment] 2024-06-25 08:20
Apparently this issue is related to nginx revese proxy.

**Comment by colinl** [comment] 2024-07-20 15:54
Is the problem now resolved?

**Comment by QBANIN** [comment] 2024-07-20 16:46
I did not find a solution so unfortunately not solved.

**Comment by colinl** [comment] 2024-07-20 17:03
I am closing this as the problem is not specific to the gauge node.  The problem is now tracked by https://github.com/FlowFuse/node-red-dashboard/issues/1024

**Closed as completed by colinl** 2024-07-20 17:03 UTC
